#!/usr/bin/env bash
script_afp=$(realpath "${BASH_SOURCE[0]}")

# input guards

  if [ -z "$REPO_HOME" ]; then
    echo "$(script_fp):: REPO_HOME is not set."
    exit 1
  fi

  env_must_be="developer/tool🖉/env"
  if [ "$ENV" != "$env_must_be" ]; then
    echo "$(script_fp):: error: must be run in the $env_must_be environment"
    exit 1
  fi

# script local environment

  release_dp="$REPO_HOME/release"
  if [ ! -d "$release_dp" ]; then
    mkdir -p "$release_dp"
  fi

  # Function to copy and set permissions
  install_file() {
    source_fp="$1"
    target_dp="$2"
    perms="$3"

    target_file="$target_dp/$(basename "$source_fp")"

    if [ ! -f "$source_fp" ]; then
      echo "install_file:: Source file '$source_fp' does not exist."
      return 1
    fi

    if ! install -m "$perms" "$source_fp" "$target_file"; then
      echo "Error: Failed to install $(basename "$source_fp") to $target_dp"
      exit 1
    else
      echo "Installed $(basename "$source_fp") to $target_dp with permissions $perms"
    fi
  }
 
# do the release

  echo "Starting release process..."

  # # Install shell scripts
  # for script in $shell_dp/*; do
  #   install_file "$script" "$release_dp" "ug+r+x"
  # done

  dev_dp="$REPO_HOME/developer"

  # for now we punt the release
  pushd ../release >& /dev/null
  set -x
  ln -snf ../developer/amd64 amd64
  ln -snf ../developer/bash🖉 bash
  ln -snf ../developer/emacs🖉 emacs
  ln -snf ../developer/make🖉 make
  set +x
  popd >& /dev/null

echo "$(script_fp) done."
